### ISSUE TITLE
In the newest beta version, taskbar transparent effects cause task manager to not respond for a long time.

### ISSUE THREAD

**Issue by Vixb1122** [TranslucentTB/TranslucentTB#173]
Video of reproduce step : https://youtu.be/SjcYSJrlAHw

**Comment by denosawr** [comment]
Can you please link your Windows build, as well as your PC specs? (Settings -> System -> About)

**Comment by Vixb1122** [comment]
@denosawr 
The Windows specs of my three pc are as follows, The antivirus software is all Windows Defender.
## Windows specs
**Version** Windows 10 Pro (Chinese-Simplified)
**Version Code** 1803
**OS Version** 17134.167
 ## First PC's specs
**CPU** Intel(R) Core(TM) i5-4460 CPU @ 3.20GHZ 
**Memory** 8GB
## Second PC's specs(Surface Pro 4 i5 8G)
## Third PC's specs
**CPU** Intel(R) Core(TM) i7-7700 CPU @ 3.60GHZ
**Memory** 8GB

**Comment by denosawr** [comment]
I'd highly recommend you leave an issue with Microsoft Support / on the MS forums about this. While I can't actually run build 17134.167 yet (school IT dept hasn't rolled it out yet), on 17134.112 (which is also version 1803), on a 8GB i5 Surface Pro 4, I cannot observe this issue. I am also using Windows Defender.

I also haven't been able to reproduce it on a machine running 17134.167 (i5-8400, 8GB).

I think it should be noted that the language of my operating system is all English. Perhaps that could be at fault, but I have no way of testing it - @sylveon @ethanhs any possibility of help?

**Comment by Vixb1122** [comment]
@denosawr This bug can only be reproduced when the taskbar is transparent (Sure ,on the newest beta version).

**Comment by 500InternalError** [comment]
I have the same issue,and here's my configuration:
Windows Version:Windows 10 Home(Chinese Simplified)
Build Version:17134.167
PC specs:
XPS 9360
This problem happens when I open this software,even though I use the normal option...

**Comment by denosawr** [comment]
I think at this point it would be wise to first consult Microsoft Support or their forums about the issue. The reason as to why seems like a Windows specific one caused by the use of Chinese Simplified as a language, even if TTB seems to be directly causing it.

**Comment by sylveon** [comment]
I figured it out: it's something on our end. We use Windows accessibility event hooks to monitor for title changes and window destroys. The problem is that our hooks are out-of-context, which has bad performance. Opening task manager or typing in the Firefox address bar generates a lot of events fitting between the range we need to monitor, which needs to be treated. A fix to this would be:
1. Use in-context event hooks, which require DLL injection and IPC.
2. Further filter our event range to only get the events we are interested in by creating more hooks, but have their range more precise. Not a definitive fix, but should resolve most performance issues.

**Comment by sylveon** [comment]
I've pushed 0b565d0 which should fix it, please give a try to the latest AppVeyor build :)

**Comment by sylveon** [comment]
Awesome!

**Comment by farhantahir3** [comment]
So is this update live on windows store or not?

**Comment by 500InternalError** [comment]
Maybe not. I tried it yesterday and it seems that the lag still exists, you could try it on your own.

**Comment by sylveon** [comment]
It is not. I need to figure out #192 and then I'll release it
