### ISSUE TITLE
Hope add multi-screen support

### ISSUE THREAD

**Issue by watermelon915** [TranslucentTB/TranslucentTB#308]
[ ] I have checked the issue tracker if my question or bug has already been fixed or answered in another (possibly closed) issue.

 - TranslucentTB version: <win10store>
 - Windows build number: <1903>
 - Steps to reproduce: <I have two screen ,but only one screen is active now>
 - Expected results: <Both screens work at the same time>
 - Actual results: <only one screen is active now>

**Comment by sylveon** [comment]
Advanced > Refresh taskbar handles should resolve this issue
![image](https://user-images.githubusercontent.com/6440374/82231607-62cc7080-98fb-11ea-83e1-f25aeb5440eb.png)

**Comment by hypervtechnics** [comment]
Is it possible to automatically refresh the handles when there is a change with the monitors?

**Comment by sylveon** [comment]
It already does, but doesn't do it reliably.

**Comment by hypervtechnics** [comment]
How to do it more reliable?

**Comment by sylveon** [comment]
You can try building this PR https://github.com/TranslucentTB/TranslucentTB/pull/292 but I'm not a huge fan of the sleep approach. Last I checked with dev builds monitor disconnects and connects works fine, albeit the rest of the functionality is barely implemented.

**Comment by koshisan** [comment]
Unfortunately I have the same problem. Wouldn't it be possible to add an "refresh taskbar handles after monitor change delay" in milliseconds in the config file? That way everyone would be happy?

**Comment by F-Unction** [comment]
Same problem

**Comment by sylveon** [comment]
This should be fixed in the latest update, available in the Store.

**Comment by koshisan** [comment]
@sylveon Can you define "latest update"? I am not using the store but the github build - latest release there is version 4 hotfix 5 from July 2020. The software itself doesn't seem to supply a version...

However, in that version the error is definitly not fixed! A manual refresh of the task bar handles after turning on the monitors is needed most of the time (but not always!) for the transparency effect to display.

**Comment by sylveon** [comment]
Yes, I am still finalizing a few things before making a GitHub release. It should come tonight or tomorrow.

**Comment by koshisan** [comment]
Thanks for the clarification. I will wait, try it and report back again :)

**Comment by sylveon** [comment]
It's there: https://github.com/TranslucentTB/TranslucentTB/releases/tag/2021.4
